"""Bounded authenticated WH6 observation replication; installed collectors stay unchanged."""
from __future__ import annotations
import hashlib
import hmac
import json
import logging
import os
import threading
from datetime import datetime, timezone
from typing import Optional
import requests
from fastapi import APIRouter, Header, HTTPException, Query
from . import db, trading_collector_service as service
from .iron_ore_basis_snapshot_sync import _snapshot_shared_secret

router = APIRouter()
ACCOUNT = 'hongyuan_futures'
UPSTREAM = 'https://ltm-web-staging.onrender.com'
PATH = '/api/internal/trading-collector/observations'
STREAMS = {'fills': 'trading_intraday_fill_observations', 'positions': 'trading_intraday_position_observations'}
_lock = threading.Lock()
_started = False
logger = logging.getLogger(__name__)


def digest(payload):
    return hashlib.sha256(json.dumps(payload, ensure_ascii=False, sort_keys=True, separators=(',', ':')).encode()).hexdigest()


def initialize_schema(conn):
    cur = conn.cursor()
    identity = 'INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY' if db._is_pg() else 'INTEGER PRIMARY KEY AUTOINCREMENT'
    cur.execute(f'''CREATE TABLE IF NOT EXISTS trading_collector_replica_receipts (
        id {identity},
        stream TEXT NOT NULL, source_id INTEGER NOT NULL, digest TEXT NOT NULL,
        result TEXT NOT NULL, received_at TEXT NOT NULL, UNIQUE(stream, source_id))''')
    cur.execute(f'''CREATE TABLE IF NOT EXISTS trading_collector_replica_state (
        id {identity}, stream TEXT UNIQUE NOT NULL, cursor_id INTEGER NOT NULL DEFAULT 0,
        checked_at TEXT, last_error TEXT)''')
    if db._is_pg():
        db._secure_postgres_tables(cur, ('trading_collector_replica_receipts','trading_collector_replica_state'))


def require_secret(authorization):
    expected = _snapshot_shared_secret()
    supplied = authorization[7:] if authorization and authorization.startswith('Bearer ') else ''
    if not expected or not supplied or not hmac.compare_digest(expected, supplied):
        raise HTTPException(404, 'Not Found')


def export_page(stream, after):
    if service._runtime_environment() != 'staging' or stream not in STREAMS or after < 0:
        raise HTTPException(404, 'Not Found')
    with db.connect() as conn:
        rows = db._exec(conn.cursor(), f'''SELECT o.id, o.device_id, o.payload_json
            FROM {STREAMS[stream]} o JOIN trading_accounts a ON a.id=o.account_id
            WHERE a.account_code=? AND o.id>? ORDER BY o.id LIMIT 100''', (ACCOUNT, after)).fetchall()
    records=[]
    for row in rows:
        payload=json.loads(row['payload_json'])
        records.append({'source_id':row['id'], 'device_id':row['device_id'], 'payload':payload,'digest':digest(payload)})
    return {'schema_version':1,'environment':'staging','account_code':ACCOUNT,'stream':stream,
            'records':records,'after':after,'next_cursor':records[-1]['source_id'] if records else after}


@router.get(PATH)
def observations(stream: str = Query('fills'), after: int = Query(0, ge=0), authorization: Optional[str] = Header(None)):
    require_secret(authorization)
    return export_page(stream, after)


def _replica_device(source_device):
    secret = _snapshot_shared_secret()
    if not secret:
        raise ValueError('replication secret unavailable')
    if not isinstance(source_device,int) or isinstance(source_device,bool) or source_device < 1:
        raise ValueError('invalid source device')
    fingerprint=f'staging-replica:{ACCOUNT}:{source_device}'
    token=hmac.new(secret.encode(),fingerprint.encode(),hashlib.sha256).hexdigest()
    with db.connect() as conn:
        cur=conn.cursor()
        account=db._exec(cur,'SELECT id FROM trading_accounts WHERE account_code=? AND is_active=1',(ACCOUNT,)).fetchone()
        if not account:raise ValueError('replication account unavailable')
        existing=db._exec(cur,'SELECT id,environment,status FROM trading_collector_devices WHERE token_hash=?',(service._hash(token),)).fetchone()
        if existing and (existing['environment']!='production' or existing['status']!='active'):
            raise ValueError('replication identity unavailable')
        if not existing:
            db._exec(cur,'''INSERT INTO trading_collector_devices
                (account_id,environment,device_name,client_version,fingerprint,token_hash,status,bound_at,last_seen_at)
                VALUES (?,'production',?,'0.3.2',?,?,'active',?,?)''',
                (account['id'],f'服务端同步（原设备 {source_device}）',fingerprint,service._hash(token),service._now(),service._now()))
    return token


def apply_page(stream, page, *, audit=False):
    if service._runtime_environment()!='production':raise ValueError('follower must be production')
    if stream not in STREAMS or page.get('schema_version')!=1 or page.get('environment')!='staging' or page.get('account_code')!=ACCOUNT or page.get('stream')!=stream:
        raise ValueError('invalid replication envelope')
    rows=page.get('records')
    if not isinstance(rows,list) or len(rows)>100:raise ValueError('invalid replication batch')
    previous=page.get('after')
    if not isinstance(previous,int) or previous<0:raise ValueError('invalid source cursor')
    for row in rows:
        sid=row.get('source_id')
        if not isinstance(sid,int) or sid<=previous or not isinstance(row.get('payload'),dict) or digest(row['payload'])!=row.get('digest'):
            raise ValueError('invalid replication record')
        previous=sid
    expected_cursor=previous
    if page.get('next_cursor')!=expected_cursor:raise ValueError('invalid next cursor')
    imported=0
    receipts={}
    if rows:
        with db.connect() as conn:
            marks=','.join('?' for _ in rows)
            found=db._exec(conn.cursor(),f'SELECT source_id,digest FROM trading_collector_replica_receipts WHERE stream=? AND source_id IN ({marks})',(stream, *(row['source_id'] for row in rows))).fetchall()
            receipts={r['source_id']:r for r in found}
    for row in rows:
        receipt=receipts.get(row['source_id'])
        if receipt:
            if receipt['digest']!=row['digest']:raise ValueError('source observation changed; review required')
            continue
        token=_replica_device(row['device_id'])
        # Ingest commits before receipt. A crash between them replays safely via existing deduplication.
        result=service.ingest_observations(token,[row['payload']] if stream=='fills' else [],[row['payload']] if stream=='positions' else [])
        if result.quarantined or result.position_quarantined:
            raise ValueError('replication record rejected; review required')
        status=json.dumps(result.__dict__,ensure_ascii=False,default=str)
        with db.connect() as conn:
            db._exec(conn.cursor(),'''INSERT OR IGNORE INTO trading_collector_replica_receipts
                (stream,source_id,digest,result,received_at) VALUES (?,?,?,?,?)''',
                (stream,row['source_id'],row['digest'],status,service._now()))
        imported+=1
    state_key=stream+':audit' if audit else stream
    saved_cursor=0 if audit and not rows else expected_cursor
    with db.connect() as conn:
        db._exec(conn.cursor(),'''INSERT INTO trading_collector_replica_state(stream,cursor_id,checked_at,last_error)
            VALUES (?,?,?,NULL) ON CONFLICT(stream) DO UPDATE SET cursor_id=excluded.cursor_id,checked_at=excluded.checked_at,last_error=NULL''',
            (state_key,saved_cursor,service._now()))
    return {'imported':imported,'cursor':saved_cursor}


def _fetch_and_apply(stream, *, audit=False):
    state_key=stream+':audit' if audit else stream
    with db.connect() as conn:
        row=db._exec(conn.cursor(),'SELECT cursor_id FROM trading_collector_replica_state WHERE stream=?',(state_key,)).fetchone()
    cursor=int(row['cursor_id']) if row else 0
    response=requests.get(UPSTREAM+PATH,params={'stream':stream,'after':cursor},headers={'Authorization':'Bearer '+_snapshot_shared_secret()},timeout=(5,30))
    if response.status_code!=200:raise ValueError('upstream unavailable HTTP '+str(response.status_code))
    page=response.json()
    apply_page(stream,page,audit=audit)
    return len(page['records'])


def sync_once():
    if service._runtime_environment()!='production':raise ValueError('follower must be production')
    with _lock:
        for stream in STREAMS:
            for _ in range(10):
                if _fetch_and_apply(stream)<100:break
            # Independent bounded rescan catches delayed commits with IDs below the live cursor.
            _fetch_and_apply(stream,audit=True)


def start_scheduler():
    global _started
    if service._runtime_environment()!='production' or os.getenv('WH6_REPLICATION_ENABLED','').lower()!='true' or _started:
        return
    _started=True
    def run():
        while True:
            try:sync_once()
            except Exception as exc:
                # Never include request headers, credentials, or source payloads in logs.
                logger.warning('WH6 replication pending retry: %s',type(exc).__name__)
                try:
                    with db.connect() as conn:
                        for stream in STREAMS:
                            db._exec(conn.cursor(),'''INSERT INTO trading_collector_replica_state(stream,cursor_id,last_error) VALUES (?,0,?)
                                ON CONFLICT(stream) DO UPDATE SET last_error=excluded.last_error''',(stream,'同步失败，等待重试'))
                except Exception:
                    logger.warning('WH6 replication state unavailable; retry retained')
            threading.Event().wait(10)
    threading.Thread(target=run,daemon=True,name='wh6-replication').start()


def get_status():
    enabled=service._runtime_environment()=='production' and os.getenv('WH6_REPLICATION_ENABLED','').lower()=='true'
    with db.connect() as conn:
        states=db._exec(conn.cursor(),"SELECT stream,checked_at,last_error FROM trading_collector_replica_state WHERE stream IN ('fills','positions')").fetchall()
        count=db._exec(conn.cursor(),'SELECT count(*) AS n FROM trading_collector_replica_receipts').fetchone()['n']
    return {'enabled':enabled,'environment':service._runtime_environment(),'received_observations':count,'streams':[dict(row) for row in states]}
