-- WH6 V2 intraday position snapshots: LTM WEB STAGING only.
-- The collector stores futures and options, while the first read surface
-- filters to options. No settlement or trading-control table is changed here.

create table if not exists public.trading_intraday_position_observations (
  id integer generated by default as identity primary key,
  device_id integer not null references public.trading_collector_devices(id),
  account_id integer not null references public.trading_accounts(id),
  source_snapshot_key text not null,
  snapshot_hash text not null,
  payload_json text not null,
  status text not null default 'accepted',
  observed_at text,
  received_at text default current_timestamp,
  unique (device_id, source_snapshot_key, snapshot_hash)
);

create table if not exists public.trading_intraday_position_snapshots (
  id integer generated by default as identity primary key,
  account_id integer not null references public.trading_accounts(id),
  source_snapshot_key text not null,
  trade_date text not null,
  snapshot_time text not null default '',
  snapshot_timestamp text not null,
  complete boolean not null default true,
  source_snapshot_sha256 text not null,
  parser_version text not null,
  data_status text not null default 'provisional',
  verification_status text not null default 'pending',
  conflict_status text not null default 'none',
  conflict_detected_at text,
  first_received_at text default current_timestamp,
  last_observed_at text default current_timestamp,
  canonical_hash text not null,
  unique (account_id, source_snapshot_key)
);

create table if not exists public.trading_intraday_position_rows (
  id integer generated by default as identity primary key,
  snapshot_id integer not null references public.trading_intraday_position_snapshots(id),
  account_id integer not null references public.trading_accounts(id),
  contract text not null,
  raw_contract text not null default '',
  asset_type text not null,
  exchange text not null,
  direction text not null,
  quantity double precision not null,
  today_quantity double precision,
  yesterday_quantity double precision,
  average_price text,
  hedge_flag text,
  option_kind text,
  underlying text,
  expiry_month text,
  strike text,
  source_record_index integer not null default 0,
  source_record_sha256 text not null,
  unique (snapshot_id, contract, direction, hedge_flag)
);

create index if not exists idx_intraday_position_observations_account
  on public.trading_intraday_position_observations(account_id, received_at);
create index if not exists idx_intraday_position_snapshots_query
  on public.trading_intraday_position_snapshots(account_id, trade_date, snapshot_timestamp);
create index if not exists idx_intraday_position_rows_query
  on public.trading_intraday_position_rows(account_id, asset_type, contract);

alter table public.trading_intraday_position_observations enable row level security;
alter table public.trading_intraday_position_snapshots enable row level security;
alter table public.trading_intraday_position_rows enable row level security;

revoke all on table
  public.trading_intraday_position_observations,
  public.trading_intraday_position_snapshots,
  public.trading_intraday_position_rows
from anon, authenticated;
