-- WH6 settlement reconciliation: Staging only.
-- Apply only to the LTM WEB STAGING Supabase project after a verified backup.
-- The application server owns these tables; browser roles receive no direct access.

alter table public.trading_trade_facts
  add column if not exists transaction_no text,
  add column if not exists normalized_transaction_no text;

alter table public.trading_intraday_fills
  add column if not exists reconciliation_status text not null default 'unmatched',
  add column if not exists settlement_identity_id integer references public.trading_fact_identities(id),
  add column if not exists settlement_batch_id integer references public.trading_import_batches(id),
  add column if not exists effective_source text not null default 'wh6',
  add column if not exists reconciled_at text;

create table if not exists public.trading_intraday_fill_reconciliations (
  id integer generated by default as identity primary key,
  intraday_fill_id integer not null references public.trading_intraday_fills(id),
  account_id integer not null references public.trading_accounts(id),
  settlement_identity_id integer references public.trading_fact_identities(id),
  settlement_batch_id integer references public.trading_import_batches(id),
  authority_type text not null,
  source_priority integer not null,
  result_status text not null,
  resolved_fields_json text not null,
  field_sources_json text not null,
  differences_json text not null,
  is_current integer not null default 1,
  created_at text default current_timestamp
);

create index if not exists idx_trading_trade_facts_settlement_key
  on public.trading_trade_facts(trade_date, exchange, normalized_transaction_no);
create index if not exists idx_intraday_fills_reconciliation_page
  on public.trading_intraday_fills(account_id, data_status, trade_date, id);
create index if not exists idx_intraday_fill_reconciliations_current
  on public.trading_intraday_fill_reconciliations(intraday_fill_id, is_current);
create index if not exists idx_intraday_fill_reconciliations_settlement
  on public.trading_intraday_fill_reconciliations(account_id, settlement_identity_id, is_current);

alter table public.trading_intraday_fill_reconciliations enable row level security;
revoke all on table public.trading_intraday_fill_reconciliations from anon, authenticated;
revoke all on sequence public.trading_intraday_fill_reconciliations_id_seq from anon, authenticated;
