-- WH6 option-fill collector: Staging only.
-- Apply this migration only to LTM WEB STAGING after local verification.
-- The application service uses the trusted server connection; anon/authenticated
-- roles receive no table or sequence privileges.

create table if not exists public.trading_collector_pairing_codes (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.trading_accounts(id),
  code_hash text not null unique,
  expires_at text not null,
  used_at text,
  created_by bigint references public.users(id),
  created_at text default current_timestamp
);

create table if not exists public.trading_collector_devices (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.trading_accounts(id),
  device_name text not null,
  client_version text not null default '',
  fingerprint text not null,
  token_hash text not null unique,
  status text not null default 'active',
  bound_at text default current_timestamp,
  last_seen_at text,
  revoked_at text,
  last_error text
);

create table if not exists public.trading_intraday_fill_observations (
  id bigint generated by default as identity primary key,
  device_id bigint not null references public.trading_collector_devices(id),
  account_id bigint not null references public.trading_accounts(id),
  source_event_key text not null,
  observation_hash text not null,
  payload_json text not null,
  status text not null default 'accepted',
  observed_at text,
  received_at text default current_timestamp,
  unique (device_id, source_event_key, observation_hash)
);

create table if not exists public.trading_intraday_fills (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.trading_accounts(id),
  source_event_key text not null,
  trade_date text not null,
  trade_time text not null default '',
  trade_timestamp text not null default '',
  exchange text not null,
  contract text not null,
  raw_contract text not null default '',
  asset_type text not null,
  side text not null,
  open_close text not null,
  quantity double precision not null,
  price text not null,
  fee text,
  turnover text,
  premium_cashflow text,
  close_profit text,
  trade_id text,
  order_id text,
  option_kind text,
  underlying text,
  expiry_month text,
  strike text,
  parser_version text not null,
  source_record_sha256 text not null,
  source_path text not null default '',
  source_record_index integer not null default 0,
  data_status text not null default 'provisional',
  verification_status text not null default 'pending',
  first_received_at text default current_timestamp,
  last_observed_at text default current_timestamp,
  canonical_hash text not null,
  unique (account_id, source_event_key)
);

create table if not exists public.trading_collector_issues (
  id bigint generated by default as identity primary key,
  device_id bigint references public.trading_collector_devices(id),
  account_id bigint references public.trading_accounts(id),
  issue_code text not null,
  source_event_key text,
  message text not null,
  payload_json text,
  created_at text default current_timestamp
);

create index if not exists idx_collector_pairing_active
  on public.trading_collector_pairing_codes(account_id, expires_at, used_at);
create index if not exists idx_collector_devices_account
  on public.trading_collector_devices(account_id, status, last_seen_at);
create index if not exists idx_collector_observations_account
  on public.trading_intraday_fill_observations(account_id, received_at);
create index if not exists idx_intraday_fills_query
  on public.trading_intraday_fills(account_id, trade_date, trade_time, contract);
create index if not exists idx_collector_issues_account
  on public.trading_collector_issues(account_id, created_at);

alter table public.trading_collector_pairing_codes enable row level security;
alter table public.trading_collector_devices enable row level security;
alter table public.trading_intraday_fill_observations enable row level security;
alter table public.trading_intraday_fills enable row level security;
alter table public.trading_collector_issues enable row level security;

revoke all on table
  public.trading_collector_pairing_codes,
  public.trading_collector_devices,
  public.trading_intraday_fill_observations,
  public.trading_intraday_fills,
  public.trading_collector_issues
from anon, authenticated;
