-- WH6 scheme A environment routing, account policy, and canonical fill identity.
-- Target: LTM WEB STAGING only. Apply after a verified logical backup/PITR point.
-- The application server uses the trusted database connection; browser roles do
-- not receive direct access to these tables.

ALTER TABLE public.trading_collector_pairing_codes
  ADD COLUMN IF NOT EXISTS environment text NOT NULL DEFAULT 'staging';

ALTER TABLE public.trading_collector_devices
  ADD COLUMN IF NOT EXISTS environment text NOT NULL DEFAULT 'staging';

UPDATE public.trading_collector_pairing_codes
SET environment = 'staging'
WHERE environment IS NULL OR btrim(environment) = '';

UPDATE public.trading_collector_devices
SET environment = 'staging'
WHERE environment IS NULL OR btrim(environment) = '';

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'trading_collector_pairing_codes_environment_check'
  ) THEN
    ALTER TABLE public.trading_collector_pairing_codes
      ADD CONSTRAINT trading_collector_pairing_codes_environment_check
      CHECK (environment IN ('staging', 'production'));
  END IF;
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'trading_collector_devices_environment_check'
  ) THEN
    ALTER TABLE public.trading_collector_devices
      ADD CONSTRAINT trading_collector_devices_environment_check
      CHECK (environment IN ('staging', 'production'));
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS public.trading_collector_account_policies (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id integer NOT NULL UNIQUE REFERENCES public.trading_accounts(id),
  environment text NOT NULL DEFAULT 'staging',
  history_start_date text NOT NULL,
  created_at text DEFAULT CURRENT_TIMESTAMP,
  updated_at text DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT trading_collector_account_policies_environment_check
    CHECK (environment IN ('staging', 'production'))
);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'trading_collector_account_policies_environment_check'
  ) THEN
    ALTER TABLE public.trading_collector_account_policies
      ADD CONSTRAINT trading_collector_account_policies_environment_check
      CHECK (environment IN ('staging', 'production'));
  END IF;
END $$;

ALTER TABLE public.trading_intraday_fills
  ADD COLUMN IF NOT EXISTS canonical_event_key text;

UPDATE public.trading_intraday_fills
SET canonical_event_key = source_event_key
WHERE canonical_event_key IS NULL OR btrim(canonical_event_key) = '';

CREATE UNIQUE INDEX IF NOT EXISTS idx_intraday_fills_account_canonical
  ON public.trading_intraday_fills(account_id, canonical_event_key);

CREATE INDEX IF NOT EXISTS idx_collector_account_policies_environment
  ON public.trading_collector_account_policies(account_id, environment);

INSERT INTO public.trading_collector_account_policies
  (account_id, environment, history_start_date, created_at, updated_at)
SELECT a.id, 'staging', '2026-09-01', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM public.trading_accounts AS a
WHERE a.account_code = 'hongyuan_futures'
ON CONFLICT (account_id) DO NOTHING;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM public.trading_collector_account_policies AS p
    JOIN public.trading_accounts AS a ON a.id = p.account_id
    WHERE a.account_code = 'hongyuan_futures'
      AND (p.environment <> 'staging' OR p.history_start_date <> '2026-09-01')
  ) THEN
    RAISE EXCEPTION
      'WH6 Staging policy baseline differs from the approved environment or history start';
  END IF;
END $$;

ALTER TABLE public.trading_collector_pairing_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_collector_devices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_collector_account_policies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_fill_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_fills ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_position_observations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_position_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_position_rows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_intraday_fill_reconciliations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.trading_collector_issues ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE
  public.trading_collector_pairing_codes,
  public.trading_collector_devices,
  public.trading_collector_account_policies,
  public.trading_intraday_fill_observations,
  public.trading_intraday_fills,
  public.trading_intraday_position_observations,
  public.trading_intraday_position_snapshots,
  public.trading_intraday_position_rows,
  public.trading_intraday_fill_reconciliations,
  public.trading_collector_issues
FROM anon, authenticated;

REVOKE ALL ON SEQUENCE
  public.trading_collector_pairing_codes_id_seq,
  public.trading_collector_devices_id_seq,
  public.trading_collector_account_policies_id_seq,
  public.trading_intraday_fill_observations_id_seq,
  public.trading_intraday_fills_id_seq,
  public.trading_intraday_position_observations_id_seq,
  public.trading_intraday_position_snapshots_id_seq,
  public.trading_intraday_position_rows_id_seq,
  public.trading_intraday_fill_reconciliations_id_seq,
  public.trading_collector_issues_id_seq
FROM anon, authenticated;

-- Keep the trusted service role as the only API-side role with direct access.
GRANT ALL ON TABLE
  public.trading_collector_pairing_codes,
  public.trading_collector_devices,
  public.trading_collector_account_policies,
  public.trading_intraday_fill_observations,
  public.trading_intraday_fills,
  public.trading_intraday_position_observations,
  public.trading_intraday_position_snapshots,
  public.trading_intraday_position_rows,
  public.trading_intraday_fill_reconciliations,
  public.trading_collector_issues
TO service_role;

GRANT USAGE, SELECT ON SEQUENCE
  public.trading_collector_pairing_codes_id_seq,
  public.trading_collector_devices_id_seq,
  public.trading_collector_account_policies_id_seq,
  public.trading_intraday_fill_observations_id_seq,
  public.trading_intraday_fills_id_seq,
  public.trading_intraday_position_observations_id_seq,
  public.trading_intraday_position_snapshots_id_seq,
  public.trading_intraday_position_rows_id_seq,
  public.trading_intraday_fill_reconciliations_id_seq,
  public.trading_collector_issues_id_seq
TO service_role;

-- Rollback guidance (forward repair is preferred):
-- 1. Restore the verified Staging backup/PITR point if any post-migration write
--    must be reverted; do not delete collector observations or facts manually.
-- 2. On a disposable copy with no newer writes, the schema-only inverse is:
--    DROP INDEX IF EXISTS public.idx_intraday_fills_account_canonical;
--    ALTER TABLE public.trading_intraday_fills DROP COLUMN IF EXISTS canonical_event_key;
--    DROP TABLE IF EXISTS public.trading_collector_account_policies;
--    ALTER TABLE public.trading_collector_devices DROP CONSTRAINT IF EXISTS trading_collector_devices_environment_check;
--    ALTER TABLE public.trading_collector_devices DROP COLUMN IF EXISTS environment;
--    ALTER TABLE public.trading_collector_pairing_codes DROP CONSTRAINT IF EXISTS trading_collector_pairing_codes_environment_check;
--    ALTER TABLE public.trading_collector_pairing_codes DROP COLUMN IF EXISTS environment;
--    Re-apply the preceding migrations and restore data from the backup if needed.
